name: update-data
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo foo
